# Generated by Django 3.1.3 on 2021-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('confirmPassword', models.TextField()),
            ],
        ),
    ]
